[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "sbg"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
sbg = ["data/*.json", "data/*.md"]

[tool.setuptools.packages.find]
where = ["src"]
